obj-m += kernel_sync_demo.o

kernel_sync_demo-y := src/main.o \
                src/params.o \
                src/worker.o \
                src/sync.o 

 ccflags-y := -I$(src)/inc \
              -Wall -Werror
